DROP DATABASE IF EXISTS FUNCIONARIOS_PROGRAMACAO;

CREATE DATABASE FUNCIONARIOS_PROGRAMACAO;

USE FUNCIONARIOS_PROGRAMACAO;

CREATE TABLE ENDERECO(
ID INT PRIMARY KEY NOT NULL auto_increment,
RUA VARCHAR(50) NOT NULL,
NUMERO VARCHAR(50)NOT NULL,
BAIRRO VARCHAR(50)NOT NULL,
CIDADE VARCHAR(50)NOT NULL
);

CREATE TABLE SALARIO(
ID INT  PRIMARY KEY NOT NULL auto_increment,
VALORES REAL,
DATAS DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TELEFONE(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT
,NUMERO BIGINT(14)  NOT NULL
); 

CREATE TABLE EQUIPE(
NOME VARCHAR(50) NOT NULL PRIMARY KEY
);

CREATE TABLE PROJETO(
CODIGO INT PRIMARY KEY NOT NULL
,NOME VARCHAR(200)
,STATUS_PROJETO ENUM ('INICIANDO','EM ANDADMENTO','FINALIZADO')
);

CREATE TABLE FUNCIONARIO(
REGISTRO INT PRIMARY KEY NOT NULL
,NOME VARCHAR(200) NOT NULL
,TELEFONE_ID INT NOT NULL
,SALARIO_ID INT NOT NULL
,ENDERECO_ID INT NOT NULL
, CONSTRAINT FK_FUNCIONARIO_TELEFONE FOREIGN KEY (TELEFONE_ID) REFERENCES TELEFONE (ID)
, CONSTRAINT FK_FUNCIONARIO_SALARIO FOREIGN KEY (SALARIO_ID) REFERENCES SALARIO (ID) 
, CONSTRAINT FK_FUNCIONARIO_ENDERECO FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ID)
);

CREATE TABLE PROGRAMADOR(
REGISTRO_ID INT NOT NULL
,FERRAMENTA_DE_PROGRAMACAO VARCHAR(200) NOT NULL DEFAULT 'IntelliJ IDEA'
,EQUIPE_NOME_COMPONENTE VARCHAR(50)
,CONSTRAINT FK_PROGRAMADOR_EQUIPE_NOME_COMPONENTE FOREIGN KEY (EQUIPE_NOME_COMPONENTE) REFERENCES EQUIPE (NOME)
,CONSTRAINT FK_PROGRAMADOR_REGISTRO FOREIGN KEY (REGISTRO_ID) REFERENCES FUNCIONARIO (REGISTRO)
);

CREATE TABLE GERENTE(
REGISTRO_ID INT NOT NULL
,EQUIPE_NOME_GERENCIANDO VARCHAR(50)
,CONSTRAINT FK_GERENTE_EQUIPE_NOME_GERENCIANDO FOREIGN KEY (EQUIPE_NOME_GERENCIANDO) REFERENCES EQUIPE (NOME)
,CONSTRAINT FK_GERENTE_REGISTRO FOREIGN KEY (REGISTRO_ID) REFERENCES FUNCIONARIO (REGISTRO)
);

SELECT*FROM FUNCIONARIO;

SELECT*FROM SALARIO;

SELECT*FROM ENDERECO;

SELECT*FROM TELEFONE;

SELECT*FROM PROGRAMADOR;

