DROP DATABASE IF EXISTS FUNCIONARIOSPROGARMACAO;

CREATE DATABASE FUNCIONARIOSPROGARMACAO;

USE FUNCIONARIOSPROGARMACAO;

CREATE TABLE ENDERECO(
ID INT PRIMARY KEY NOT NULL auto_increment,
RUA VARCHAR(50) NOT NULL,
NUMERO VARCHAR(50)NOT NULL,
BAIRRO VARCHAR(50)NOT NULL,
CIDADE VARCHAR(50)NOT NULL
);

CREATE TABLE SALARIO(
ID INT  PRIMARY KEY NOT NULL auto_increment,
VALORES REAL,
DATAS DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TELEFONE(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT
,NUMERO BIGINT(14)  NOT NULL
); 

CREATE TABLE FUNCIONARIO(
REGISTRO INT PRIMARY KEY NOT NULL,
NOME VARCHAR(200) NOT NULL,
TELEFONE_ID INT,
FERRAMENTADEPROGRAMACAO VARCHAR(200)
,SALARIO_ID INT 
,ENDERECO_ID INT
, CONSTRAINT FK_FUNCIONARIO_TELEFONE FOREIGN KEY (TELEFONE_ID) REFERENCES TELEFONE (ID)
, CONSTRAINT FK_FUNCIONARIO_SALARIO FOREIGN KEY (SALARIO_ID) REFERENCES SALARIO (ID) 
, CONSTRAINT FK_FUNCIONARIO_ENDERECO FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ID)
);

SELECT*FROM FUNCIONARIO;

SELECT*FROM SALARIO;

SELECT*FROM ENDERECO;

