USE EDITORA_BOOKS; 

SELECT*FROM LIVRO AS L
JOIN AUTOR AS AU ON L.ID_AUTOR = AU.ID ;

SELECT L.NOME, L.ANO , L.CODIGO, AU.NOME FROM LIVRO AS L
INNER JOIN AUTOR AS AU ON L.ID_AUTOR = AU.ID; 

SELECT * FROM EDITORA;

SELECT * FROM ENDERECO 
INNER JOIN EDITORA ON ENDERECO.EDITOR_CODIGO = EDITORA.CODIGO;

SELECT *  FROM TELEFONE 
INNER JOIN EDITORA ON TELEFONE.EDITOR_CODIGO = EDITORA.CODIGO;