USE EDITORA_BOOKS; 

SELECT*FROM LIVRO AS L
JOIN AUTOR AS AU ON L.ID_AUTOR = AU.ID ;

SELECT L.NOME, L.ANO , L.CODIGO, AU.NOME FROM LIVRO AS L
INNER JOIN AUTOR AS AU ON L.ID_AUTOR = AU.ID; 

SELECT * FROM EDITORA;

SELECT * FROM ENDERECO 
INNER JOIN EDITORA ON ENDERECO.EDITOR_CODIGO = EDITORA.CODIGO;

SELECT *  FROM TELEFONE 
INNER JOIN EDITORA ON TELEFONE.EDITOR_CODIGO = EDITORA.CODIGO;

SELECT*FROM EDITORA 
INNER JOIN EDICAO ON EDICAO.EDITOR_CODIGO = EDITORA.CODIGO;

SELECT*FROM EDICAO
INNER JOIN LIVRO ON LIVRO.EDICAO_ISBN = EDICAO.ISBN;

SELECT L.NOME, E.ISBN, E.PRECO, E.NUMERO_PAGINAS FROM 
EDICAO AS E
INNER JOIN LIVRO AS L
ON L.EDICAO_ISBN = E.ISBN
