DROP DATABASE IF EXISTS EDITORA_BOOKS;

CREATE DATABASE EDITORA_BOOKS;

USE EDITORA_BOOKS;

CREATE TABLE  EDITORA(
CODIGO INT NOT NULL PRIMARY KEY
,NOME VARCHAR(50)
);

CREATE TABLE TELEFONE(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT
,DDD INT(2) NOT NULL
,NUMERO VARCHAR(9) NOT NULL
,EDITOR_CODIGO INT NOT NULL
,CONSTRAINT FK_EDITOR_CODIGO FOREIGN KEY (EDITOR_CODIGO) REFERENCES EDITORA (CODIGO)
);

CREATE TABLE ENDERECO(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT
,RUA VARCHAR(20) NOT NULL
,BAIRRO VARCHAR(20) NOT NULL
,CIDADE VARCHAR(20) NOT NULL
,NUMERO VARCHAR(20) NOT NULL
,CEP VARCHAR(45) NOT NULL
,EDITOR_CODIGO INT NOT NULL
,CONSTRAINT FK_EDITOR_CODIGO_END FOREIGN KEY (EDITOR_CODIGO) REFERENCES EDITORA (CODIGO)
);

CREATE TABLE AUTOR(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT
,NOME VARCHAR(50) NOT NULL
,DATA_NASCIMENTO DATE NOT NULL
,NOTA_BIB FLOAT NOT NULL DEFAULT '0.0'
,PAIS_ORIGEM VARCHAR(25)
);

CREATE TABLE EDICAO(
ISBN INT NOT NULL PRIMARY KEY
,ANO DATE NOT NULL 
,NUMERO_PAGINAS INT NOT NULL
,QTD_ESTOQUE INT NOT NULL
,PRECO FLOAT NOT NULL
,EDITOR_CODIGO INT NOT NULL
,CONSTRAINT FK_EDITOR_CODIGO_EDI FOREIGN KEY (EDITOR_CODIGO) REFERENCES EDITORA (CODIGO)
);

CREATE TABLE LIVRO(
CODIGO INT NOT NULL PRIMARY KEY
,LINGUA VARCHAR(20) NOT NULL
,NOME VARCHAR(20) NOT NULL
,ANO DATETIME DEFAULT CURRENT_TIMESTAMP
,ID_AUTOR INT NOT NULL 
,EDICAO_ISBN INT NOT NULL
,CONSTRAINT FK_ID_AUTOR FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR (ID)
,CONSTRAINT FK_EDICAO_ISBN FOREIGN KEY (EDICAO_ISBN) REFERENCES EDICAO (ISBN)
);

INSERT INTO EDITORA (CODIGO,NOME) VALUES ('3214569','GRAL AZUL');

INSERT INTO TELEFONE (DDD,NUMERO,EDITOR_CODIGO) VALUES ('71','123456789','3214569');

INSERT INTO ENDERECO (RUA,BAIRRO,CIDADE,NUMERO,CEP,EDITOR_CODIGO) VALUES ('RIO VERDE','CASCALHO','SALVADOR','358 AC','85.540.258','3214569');

INSERT INTO AUTOR (NOME,DATA_NASCIMENTO,NOTA_BIB,PAIS_ORIGEM) VALUES ('NALBERT BASTOS','2000-08-09','4.5','BRASIL');

INSERT INTO EDICAO (ISBN,ANO,NUMERO_PAGINAS,QTD_ESTOQUE,PRECO,EDITOR_CODIGO) VALUES ('245871','2010-08-12','60','400','39.8','3214569');

INSERT INTO LIVRO (CODIGO,LINGUA,NOME,ANO,ID_AUTOR,EDICAO_ISBN) VALUES ('021','PORTUGUÊS-BR','O GRANDE INVESTIDOR','2010-11--11','1','245871');

/*SELECT*FROM EDITORA;

SELECT*FROM TELEFONE;

SELECT*FROM ENDERECO;

SELECT*FROM AUTOR;

SELECT*FROM EDICAO;

SELECT*FROM LIVRO;*/

SELECT LIVRO.NOME, LIVRO.EDICAO_ISBN, AUTOR.NOME
FROM LIVRO
INNER JOIN AUTOR
ON LIVRO.ID_AUTOR = AUTOR.ID;





