DROP DATABASE IF EXISTS EDITORA_BOOKS;

CREATE DATABASE EDITORA_BOOKS;

USE EDITORA_BOOKS;

CREATE TABLE  EDITORA(
CODIGO INT NOT NULL PRIMARY KEY
,NOME VARCHAR(50)
);

CREATE TABLE TELEFONE(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT
,DDD INT(2) NOT NULL
,NUMERO VARCHAR(9) NOT NULL
,EDITOR_CODIGO INT NOT NULL
,CONSTRAINT FK_EDITOR_CODIGO FOREIGN KEY (EDITOR_CODIGO) REFERENCES EDITORA (CODIGO)
);

CREATE TABLE ENDERECO(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT
,RUA VARCHAR(20) NOT NULL
,BAIRRO VARCHAR(20) NOT NULL
,CIDADE VARCHAR(20) NOT NULL
,NUMERO VARCHAR(20) NOT NULL
,CEP VARCHAR(45) NOT NULL
,EDITOR_CODIGO INT NOT NULL
,CONSTRAINT FK_EDITOR_CODIGO_END FOREIGN KEY (EDITOR_CODIGO) REFERENCES EDITORA (CODIGO)
);

CREATE TABLE AUTOR(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT
,NOME VARCHAR(50) NOT NULL
,DATA_NASCIMENTO DATE NOT NULL
,NOTA_BIB FLOAT NOT NULL DEFAULT '0.0'
,PAIS_ORIGEM VARCHAR(25)
);

CREATE TABLE EDICAO(
ISBN INT NOT NULL PRIMARY KEY
,ANO DATE NOT NULL 
,NUMERO_PAGINAS INT NOT NULL
,QTD_ESTOQUE INT NOT NULL
,PRECO FLOAT NOT NULL
,EDITOR_CODIGO INT NOT NULL
,CONSTRAINT FK_EDITOR_CODIGO_EDI FOREIGN KEY (EDITOR_CODIGO) REFERENCES EDITORA (CODIGO)
);

CREATE TABLE LIVRO(
CODIGO INT NOT NULL PRIMARY KEY
,LINGUA VARCHAR(20) NOT NULL
,NOME VARCHAR(20) NOT NULL
,ANO DATETIME DEFAULT CURRENT_TIMESTAMP
,ID_AUTOR INT NOT NULL 
,EDICAO_ISBN INT NOT NULL
,CONSTRAINT FK_ID_AUTOR FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR (ID)
,CONSTRAINT FK_EDICAO_ISBN FOREIGN KEY (EDICAO_ISBN) REFERENCES EDICAO (ISBN)
);



